name: android Release


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "3.7.3"
  steps:
  - uses: subosito/flutter-action@v2
    with:
      channel: 'stable'
  - run: flutter --version