name: android Release


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:


job:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
        channel: 'stable'
    - run: flutter '3.0.5'
    - run: flutter test
    - run: flutter build apk
    - run: flutter build appbundle
